[project]
name = "astroglial-morphology"
version = "0.1.0"
description = ""
authors = [
    {name = "Javid Rezai",email = "javid.af@outlook.com"}
]
readme = "README.md"
requires-python = ">=3.9,<3.11"
dependencies = [
    "scikit-image (>=0.24,<0.25)",
    "pillow (>=11.3.0,<12.0.0)",
    "ipykernel (>=6.30.1,<7.0.0)",
    "numpy (>=2.0.2,<3.0.0)",
    "matplotlib (>=3.9.4,<4.0.0)",
    "cellpose (>=3.1.1.2,<4.0.0.0)",
    "suite2p (==0.14.5)",
    "astroglial-analysis @ git+https://github.com/yaksilab/silver-dollop.git",

]

[tool.poetry]
packages = [{include = "astroglial_morphology", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
